[package]
name = "site-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
color-eyre = "0.6.3"
gray_matter = "0.2.8"
serde = { version = "1.0.203", features = ["derive"] }
